### ISSUE TITLE
Automate updating the running docker containers on the server

### ISSUE THREAD

**Issue by arulagrawal** [COS301-SE-2022/Office-Booker#332]
There's an additional part that I'll make a separate pr for, which is to automatically update the server with the new image versions.

Gotta wait till I'm back in SA, because I don't have the SSH key for the AWS server on me at the moment

_Originally posted by @arulagrawal in https://github.com/COS301-SE-2022/Office-Booker/issues/331#issuecomment-1252769478_

**Comment by brettdup** [comment]
Any update on this?
